#!/usr/bin/env bash
# script that configures a new Ubuntu machine to Install nginx on your web-01 listening on port 80
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
