#!/usr/bin/env bash
# configuring ubuntu server as follows below:
# changing localhost to 127.0.0.2
# resolving facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
